CREATE TABLE caja_chica (
id INT NOT NULL AUTO_INCREMENT,
usuario VARCHAR(100) NOT NULL,
num_os INT NOT NULL,
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
centro_costo VARCHAR(150) NOT NULL,
descripcion VARCHAR(250) NOT NULL,
proveedor VARCHAR(100) NOT NULL,
documento VARCHAR(100) NULL,
monto DECIMAL(20,2) NOT NULL,
creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
actualizado DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=INNODB;
