CREATE TABLE caja_chica (
id INT NOT NULL AUTO_INCREMENT,
tipo VARCHAR(15) NOT NULL,
usuario VARCHAR(100) NOT NULL,
num_os INT NOT NULL,
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
centro_costo VARCHAR(150) NOT NULL,
descripcion VARCHAR(250) NOT NULL,
proveedor VARCHAR(100) NOT NULL,
documento VARCHAR(100) NULL,
monto DECIMAL(20,2) NOT NULL,
creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
actualizado DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=INNODB;



CREATE TABLE caja_chica_obs (
id INT NOT NULL AUTO_INCREMENT,
num_os VARCHAR(20) NOT NULL,
observaciones VARCHAR(250) NOT NULL,
creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)ENGINE=INNODB;



CREATE TABLE caja_chica_adj (
id INT NOT NULL AUTO_INCREMENT,
num_os VARCHAR(20) NOT NULL,
archivo VARCHAR(250) NOT NULL,
creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)ENGINE=INNODB;
