
INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(1, 101, 'PERSONAL DE ADMINISTRACION Y FINANZAS'),
	(1, 102, 'ALOJAMIENTO'),
	(1, 103, 'PASAJES AEREOS Y TERRESTES'),
	(1, 104, 'COMBUSTIBLE ESTACIONAMIENTO Y PEAJES'),
	(1, 105, 'VIATICOS'),
	(1, 106, 'GASTOS SERVICIOS BASICOS '),
	(1, 107, 'GASTOS INFRAESTRUCTURA GENERAL'),
	(1, 108, 'EXISTENCIAS'),
	(1, 109, 'INSUMOS COMPUTACIONALES');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(2, 201, 'PERSONAL GERENCIA DE MARKETING'),
	(2, 202, 'GASTOS DE ADMINISTRACIÓN'),
	(2, 203, 'ALOJAMIENTO'),
	(2, 204, 'PASAJES AEREOS Y TERRESTES'),
	(2, 205, 'COMBUSTIBLE, ESTACIONAMIENTO Y PEAJES'),
	(2, 206, 'VIATICOS'),
	(2, 207, 'GASTOS MARKETING REUTECH'),
	(2, 208, 'PERSONAL MARKETING REUTECH'),
	(2, 209, 'GASTOS ADMINISTRACIÓN REUTECH'),
	(2, 210, 'GASTOS HOTELERÍA REUTECH'),
	(2, 211, 'GASTOS PUBLICIDAD REUTECH'),
	(2, 212, 'GASTOS ESTACIONAMIENTOS REUTECH');


INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(3, 301, 'PERSONAL GERENCIA DE OPERACIONES'),
	(3, 302, 'VIATICOS '),
	(3, 303, 'REPARACION Y MANTENCION EQUIPOS'),
	(3, 304, 'REPARACION Y MANTENCION VEHICULOS'),
	(3, 305, 'MANTENCION E INSUMOS VEHICULOS'),
	(3, 306, 'GASTOS DE ADMINISTRACION '),
	(3, 307, 'ALOJAMIENTO'),
	(3, 308, 'PASAJES AEREOS Y TERRESTRES'),
	(3, 309, 'COMBUSTIBLE, ESTACIONAMIENTO Y PEAJES'),
	(3, 310, 'INSUMOS Y REPUESTOS OPERACIONES');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(4, 401, 'PROYECTOS ESPECIALES'),
	(4, 402, 'SENSEMETRICS'),
	(4, 403, 'INVESTIGACION Y DESARROLLO DE PRODUCTOS'),
	(4, 404, 'TIDELAND'),
	(4, 405, 'REUTECH'),
	(4, 406, 'CCTV CENTINELA TERMAL'),
	(4, 407, 'CARRO ESTÁNDAR'),
	(4, 408, 'CARRO UMET2'),
	(4, 409, 'UMETs CUAJONES'),
	(4, 410, 'CARROS DE STOCK'),
	(4, 411, 'CARROS ODIN - CENTINELA'),
	(4, 412, 'HOUSING E-MINING'),
	(4, 413, 'MARCOBRE - PERU'),
	(4, 414, 'ORDEN ODIN 3 CARROS');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(5, 501, 'PERSONAL FAENA LOS BRONCES'),
	(5, 502, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(5, 503, 'COMBUSTIBLE'),
	(5, 504, 'PASAJES AEREOS Y TERRESTES'),
	(5, 505, 'VIATICOS TECNICOS'),
	(5, 506, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA LOS BRONCES '),
	(5, 507, 'MOVILIZACION FAENA LOS BRONCES'),
	(5, 508, 'ALIMENTACION FAENA LOS BRONCES'),
	(5, 509, 'INSUMOS Y REPUESTOS FAENA LOS BRONCES'),
	(5, 510, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(6, 601, 'PERSONAL FAENA LOS COLORADOS'),
	(6, 602, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(6, 603, 'COMBUSTIBLE'),
	(6, 604, 'PASAJES AEREOS Y TERRESTES'),
	(6, 605, 'VIATICOS TECNICOS'),
	(6, 606, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA LOS COLORADOS'),
	(6, 607, 'MOVILIZACION FAENA LOS COLORADOS'),
	(6, 608, 'ALIMENTACION FAENA LOS COLORADOS'),
	(6, 609, 'INSUMOS Y REPUESTOS FAENA LOS COLORADOS'),
	(6, 610, 'MANTENCION E INSUMO VEHICULO');


INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(7, 701, 'PERSONAL FAENA EL ROMERAL'),
	(7, 702, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(7, 703, 'COMBUSTIBLE'),
	(7, 704, 'PASAJES AEREOS Y TERRESTES'),
	(7, 705, 'VIATICOS TECNICOS'),
	(7, 706, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA EL ROMERAL'),
	(7, 707, 'MOVILIZACION FAENA EL ROMERAL'),
	(7, 708, 'ALIMENTACION FAENA EL ROMERAL'),
	(7, 709, 'INSUMOS Y REPUESTOS FAENA EL ROMERAL'),
	(7, 710, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES
	(8, 801, 'PERSONAL FAENA '),
	(8, 802, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(8, 803, 'COMBUSTIBLE'),
	(8, 804, 'PASAJES AEREOS Y TERRESTES'),
	(8, 805, 'VIATICOS TECNICOS'),
	(8, 806, 'GASTOS DE ADMINISTRACION Y OPERACIONES '),
	(8, 807, 'MOVILIZACION CENTINELA'),
	(8, 808, 'ALIMENTACION CENTINELA'),
	(8, 809, 'INSUMOS Y REPUESTOS CENTINELA'),
	(8, 810, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(9, 901, 'PERSONAL FAENA QUEBRADA BLANCA'),
	(9, 902, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(9, 903, 'COMBUSTIBLE'),
	(9, 904, 'PASAJES AEREOS Y TERRESTES'),
	(9, 905, 'VIATICOS TECNICOS'),
	(9, 906, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA QUEBRADA BLANCA'),
	(9, 907, 'MOVILIZACION FAENA QUEBRADA BLANCA'),
	(9, 908, 'ALIMENTACION FAENA QUEBRADA BLANCA'),
	(9, 909, 'INSUMOS Y REPUESTOS FAENA QUEBRADA BLANCA'),
	(9, 910, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(10, 1001, 'PERSONAL FAENA ZALDIVAR'),
	(10, 1002, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(10, 1003, 'COMBUSTIBLE'),
	(10, 1004, 'PASAJES AEREOS Y TERRESTES'),
	(10, 1005, 'VIATICOS TECNICOS'),
	(10, 1006, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA ZALDIVAR'),
	(10, 1007, 'MOVILIZACION FAENA ZALDIVAR'),
	(10, 1008, 'ALIMENTACION FAENA ZALDIVAR'),
	(10, 1009, 'INSUMOS Y REPUESTOS FAENA ZALDIVAR'),
	(10, 1010, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(11, 1101, 'PERSONAL FAENA ESCONDIDA'),
	(11, 1102, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(11, 1103, 'COMBUSTIBLE'),
	(11, 1104, 'PASAJES AEREOS Y TERRESTES'),
	(11, 1105, 'VIATICOS TECNICOS'),
	(11, 1106, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA ESCONDIDA'),
	(11, 1107, 'MOVILIZACION FAENA ESCONDIDA'),
	(11, 1108, 'ALIMENTACION FAENA ESCONDIDA'),
	(11, 1109, 'INSUMOS Y REPUESTOS FAENA ESCONDIDA'),
	(11, 1110, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(12, 1201, 'PERSONAL ASIGNADO A PERU'),
	(12, 1202, 'ALOJAMIENTO TECNICO Y PERSONAL PERU'),
	(12, 1203, 'PASAJES AEREOS HACIA PERU');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(13, 1301, 'PERSONAL FAENA LOMAS BAYAS'),
	(13, 1302, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(13, 1303, 'COMBUSTIBLE'),
	(13, 1304, 'PASAJES AEREOS Y TERRESTES'),
	(13, 1305, 'VIATICOS TECNICOS'),
	(13, 1306, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA LOMAS BAYAS'),
	(13, 1307, 'MOVILIZACION FAENA LOMAS BAYAS'),
	(13, 1308, 'ALIMENTACION FAENA LOMAS BAYAS'),
	(13, 1309, 'INSUMOS Y REPUESTOS FAENA LOMAS BAYAS'),
	(13, 1310, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(14, 1401, 'PERSONAL FAENA CERRO COLORADO'),
	(14, 1402, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(14, 1403, 'COMBUSTIBLE'),
	(14, 1404, 'PASAJES AEREOS Y TERRESTES'),
	(14, 1405, 'VIATICOS TECNICOS'),
	(14, 1406, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA CERRO COLORADO'),
	(14, 1407, 'MOVILIZACION FAENA CERRO COLORADO'),
	(14, 1408, 'ALIMENTACION FAENA CERRO COLORADO'),
	(14, 1409, 'INSUMOS Y REPUESTOS FAENA CERRO COLORADO'),
	(14, 1410, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(15, 1501, 'PERSONAL FAENA CARMEN DE ANDACOLLO'),
	(15, 1502, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(15, 1503, 'COMBUSTIBLE'),
	(15, 1504, 'PASAJES AEREOS Y TERRESTES'),
	(15, 1505, 'VIATICOS TECNICOS'),
	(15, 1506, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA CARMEN DE ANDACOLLO'),
	(15, 1507, 'MOVILIZACION FAENA CARMEN DE ANDACOLLO'),
	(15, 1508, 'ALIMENTACION FAENA CARMEN DE ANDACOLLO'),
	(15, 1509, 'INSUMOS Y REPUESTOS FAENA CARMEN DE ANDACOLLO'),
	(15, 1510, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(16, 1601, 'PERSONAL FAENA EL SOLDADO'),
	(16, 1602, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(16, 1603, 'COMBUSTIBLE'),
	(16, 1604, 'PASAJES AEREOS Y TERRESTES'),
	(16, 1605, 'VIATICOS TECNICOS'),
	(16, 1606, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA EL SOLDADO'),
	(16, 1607, 'MOVILIZACION FAENA EL SOLDADO'),
	(16, 1608, 'ALIMENTACION FAENA EL SOLDADO'),
	(16, 1609, 'INSUMOS Y REPUESTOS FAENA EL SOLDADO'),
	(16, 1610, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(17, 1701, 'PERSONAL FAENA SPENCE'),
	(17, 1702, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(17, 1703, 'COMBUSTIBLE'),
	(17, 1704, 'PASAJES AEREOS Y TERRESTES'),
	(17, 1705, 'VIATICOS TECNICOS'),
	(17, 1706, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA SPENCE'),
	(17, 1707, 'MOVILIZACION FAENA SPENCE'),
	(17, 1708, 'ALIMENTACION FAENA SPENCE'),
	(17, 1709, 'INSUMOS Y REPUESTOS FAENA SPENCE'),
	(17, 1710, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(18, 1801, 'PERSONAL FAENA CEMIN UVA'),
	(18, 1802, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(18, 1803, 'COMBUSTIBLE'),
	(18, 1804, 'PASAJES AEREOS Y TERRESTES'),
	(18, 1805, 'VIATICOS TECNICOS'),
	(18, 1806, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA CEMIN UVA'),
	(18, 1807, 'MOVILIZACION FAENA CEMIN UVA'),
	(18, 1808, 'ALIMENTACION FAENA CEMIN UVA'),
	(18, 1809, 'INSUMOS Y REPUESTOS FAENA CEMIN UVA'),
	(18, 1810, 'MANTENCION E INSUMO VEHICULO');

INSERT INTO categ_chile (mina_cl_id, codigo, categoria) VALUES 
	(19, 1901, 'PERSONAL FAENA LA COIPA'),
	(19, 1902, 'ALOJAMIENTOS TÉCNICOS Y PERSONAL CLONSA'),
	(19, 1903, 'COMBUSTIBLE'),
	(19, 1904, 'PASAJES AEREOS Y TERRESTES'),
	(19, 1905, 'VIATICOS TECNICOS'),
	(19, 1906, 'GASTOS DE ADMINISTRACION Y OPERACIONES FAENA LA COIPA'),
	(19, 1907, 'MOVILIZACION FAENA LA COIPA'),
	(19, 1908, 'ALIMENTACION FAENA LA COIPA'),
	(19, 1909, 'INSUMOS Y REPUESTOS FAENA LA COIPA'),
	(19, 1910, 'MANTENCION E INSUMO VEHICULO');